# -*- coding: utf-8 -*-
"""hugging_face_day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IMQ6xgq3DqUb59Fgu3sYDpowOs0Oloq
"""

from transformers import pipeline

classifier=pipeline("sentiment-analysis")
classifier("i hate you")

classifier=pipeline("zero-shot-classification", model="facebook/bart-large-mnli")
classifier("This is a course about the transformers library",
           candidate_labels=["education","politics","business"])

generator=pipeline("text-generation",model="distilgpt2")
generator("i play football", max_new_tokens=30, num_return_sequences=2, clean_up_tokenization_spaces=False)

unmasker= pipeline("fill-mask")
unmasker("the course will teach you all about <mask> models.",top_k=2)

ner=pipeline("ner", model="dbmdz/bert-large-cased-finetuned-conll03-english")
ner("My name is Rohit and i worked at Huggingface in Sylhet")

from transformers import pipeline

question_answerer=pipeline("question-answering")
question_answerer(
    question="Where do I work?",
    context="My name is Rohit and i worked at Huggingface in Sylhet")

!pip install -U transformers

from transformers import pipeline

summarizer = pipeline(
    "text-generation",
    model="facebook/bart-large-cnn"
)

text = """The central person, idea, or issue discussed in the text."""

result = summarizer(text, max_new_tokens=50)

print(result[0]["generated_text"])

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "facebook/bart-large-cnn"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

text = """
Artificial intelligence is transforming many industries.
Companies are using AI to automate tasks, analyze data,
and build intelligent applications.
"""

inputs = tokenizer(
    text,
    return_tensors="pt",
    truncation=True
)

summary_ids = model.generate(
    **inputs,
    max_new_tokens=50
)

summary = tokenizer.decode(
    summary_ids[0],
    skip_special_tokens=True
)

print(summary)

import transformers

print(transformers.__version__)

!pip install transformers==4.57.1

summarizer= pipeline("summarization")
summarizer("""The central person, idea, or issue discussed in the text (such as "illegal immigration" or "loyalty in literature""")

translator= pipeline("translation_en_to_de")
translator("Hugging Face is a technology company based in New York and Paris")

from transformers import AutoTokenizer

checkpoint="distilbert-base-uncased-finetuned-sst-2-english"
tokenizer= AutoTokenizer.from_pretrained(checkpoint)

raw_input=["i've been waiting for a huggingface copurse","i hate this"]
inputs= tokenizer(raw_input, padding=True, truncation=True, return_tensors="pt")
print(inputs)

from transformers import AutoTokenizer,AutoModel

tokenizer= AutoTokenizer.from_pretrained("bert-base-cased")
model= AutoModel.from_pretrained("bert-base-cased")

text=" I love Bangladesh"
inputs= tokenizer(text, return_tensors="pt")
outputs= model(**inputs)
print(outputs.last_hidden_state.shape)

from transformers import BertConfig
bert_config= BertConfig.from_pretrained("bert-base-cased")
print(bert_config)

tokenizer= AutoTokenizer.from_pretrained("bert-base-cased")
tokens= tokenizer.tokenize("Let's try to tokenize!")
print(tokens)

tokenizer= AutoTokenizer.from_pretrained("albert-base-v2")
tokens= tokenizer.tokenize("Let's try to tokenize!")
print(tokens)

tokenizer= AutoTokenizer.from_pretrained("bert-base-cased")
tokens= tokenizer.tokenize("Let's try to tokenize!")
input_ids=tokenizer.convert_tokens_to_ids(tokens)
print(input_ids)

tokenizer= AutoTokenizer.from_pretrained("bert-base-cased")
tokens= tokenizer("Let's try to tokenize!")
print(tokenizer.decode(tokens["input_ids"]))