# -*- coding: utf-8 -*-
"""MODEL_TRAINING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7sqMHS7iyPxGTNUWYL2As_U77c_jw_L
"""

from datasets import load_dataset

raw_datasets = load_dataset("nyu-mll/glue", "mnli")
raw_datasets

raw_datasets["train"].unique("label")

raw_datasets["train"][6]

raw_datasets["train"][:10]

raw_datasets["train"].features

from transformers import AutoTokenizer
checkpoint="bert-base-cased"
tokenizer= AutoTokenizer.from_pretrained(checkpoint)
def tokenize_function(example):
  return tokenizer(example["premise"], example["hypothesis"], truncation=True)
tokenized_datasets= raw_datasets.map(tokenize_function,batched=True)
print(tokenized_datasets.column_names)

print(tokenized_datasets["train"][:10])

tokenized_datasets["train"]["input_ids"]

[len(x) for x in tokenized_datasets["train"]["input_ids"][:10]]

tokenized_datasets= tokenized_datasets.remove_columns(["idx","premise","hypothesis"])
tokenized_datasets= tokenized_datasets.rename_columns({"label":"labels"})
tokenized_datasets.set_format("torch")
tokenized_datasets["train"]

small_train_dataset= tokenized_datasets["train"].select(range(100))
print(small_train_dataset)

import sys
print("torchvision" in sys.modules)

from torch.utils.data import DataLoader

from transformers import DataCollatorWithPadding

data_collator= DataCollatorWithPadding(tokenizer=tokenizer)
train_dataloader=DataLoader(tokenized_datasets["train"],shuffle=True,batch_size=16,collate_fn=data_collator)
for step,batch in enumerate(train_dataloader):
  print(batch["input_ids"].shape)
  if step>5:
    break

from transformers import AutoModelForSequenceClassification
from transformers import TrainingArguments

checkpoint="bert-base-cased"
model= AutoModelForSequenceClassification.from_pretrained(checkpoint,num_labels=3)
training_args= TrainingArguments(
    "test-trainer", per_device_train_batch_size=16, per_device_eval_batch_size=16, num_train_epochs=5,
    learning_rate=2e-5
)

print(model.config.num_labels)

model.config.problem_type = "single_label_classification"

import torch
from transformers import Trainer, DataCollatorWithPadding

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=tokenized_datasets["validation_matched"],
    data_collator=data_collator,

)

trainer.train()

small_validation = tokenized_datasets["validation_matched"].select(range(100))

predictions = trainer.predict(small_validation)

print(predictions.predictions.shape)
print(predictions.label_ids.shape)

!pip install evaluate

import numpy as np
import evaluate

metric = evaluate.load("glue", "mnli")

preds = np.argmax(predictions.predictions, axis=-1)

result = metric.compute(
    predictions=preds,
    references=predictions.label_ids
)

print(result)

